# UGCT Esole-Yau Ewx exceptional-sector Chow reduction
# Runs under SageMath.
#
# Input:
#   data/esole_yau_ewx_resolved_ambient_chow.json
#
# Output:
#   data/esole_yau_exceptional_reduction_rules.json
#   reports/exceptional_chow_compute_report.json
#
# This reducer uses direct exported values if supplied. Otherwise it uses the
# Sage quotient presentation, auxiliary class substitution, Cartan-pair
# pushforward, and named vanishing rules before declaring a monomial unresolved.

import itertools
import json
from fractions import Fraction
from pathlib import Path

try:
    from sage.all import PolynomialRing, QQ
except Exception:
    PolynomialRing = None
    QQ = None

DATA = Path("data")
REPORTS = Path("reports")
DATA.mkdir(exist_ok=True)
REPORTS.mkdir(exist_ok=True)

INPUT = DATA / "esole_yau_ewx_resolved_ambient_chow.json"
RULES_OUT = DATA / "esole_yau_exceptional_reduction_rules.json"
REPORT_OUT = REPORTS / "exceptional_chow_compute_report.json"

basis = ["R", "H"] + [f"E{i}" for i in range(1, 9)] + ["Z"] + [f"C{i}" for i in range(1, 5)]
order = {name: i for i, name in enumerate(basis)}
CARTAN = {"C1", "C2", "C3", "C4"}
ZERO_SECTION_NAMES = {"Z", "z"}
BASE_NAMES = {"R", "H"} | {f"E{i}" for i in range(1, 9)}
required_keys = ["status", "resolution_chamber", "basis", "ambient_variables", "divisor_classes", "sr_ideal_generators", "linear_equivalence_generators", "proper_transform_class", "hypersurface_class", "integration_rules"]

A4 = [
    [2, -1, 0, 0],
    [-1, 2, -1, 0],
    [0, -1, 2, -1],
    [0, 0, -1, 2],
]

stats = {
    "single_cartan_pushforward_zero_terms": 0,
    "zero_section_cartan_disjoint_terms": 0,
    "auxiliary_substitution_passes": 0,
    "cartan_pair_pushforward_terms": 0,
    "higher_cartan_unresolved_terms": 0
}

def canonical_key(items):
    return ",".join(sorted(items, key=lambda x: order[x]))

def supported_by_direct_rules(mon):
    cart_count = sum(1 for x in mon if x.startswith("C"))
    if cart_count == 0:
        return True
    if cart_count == 2:
        cart = [x for x in mon if x.startswith("C")]
        non = [x for x in mon if not x.startswith("C")]
        return len(cart) == 2 and "Z" not in non and len(non) == 2
    return False

def exceptional_slots():
    return [canonical_key(mon) for mon in itertools.combinations_with_replacement(basis, 4) if not supported_by_direct_rules(mon)]

def pending_rule_template(slots, status, source, rules=None, missing_values=None):
    rules = rules or {}
    missing_values = missing_values if missing_values is not None else [k for k in slots if k not in rules]
    return {
        "schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1",
        "status": status,
        "resolution_chamber": "Esole-Yau Ewx",
        "source": source,
        "rules": rules,
        "required_rules": {k: "EXACT_VALUE_REQUIRED_FROM_FULL_CHOW_REDUCTION" for k in missing_values},
        "rule_count": len(rules),
        "required_rule_count": len(missing_values),
        "total_exceptional_slots": len(slots)
    }

def write_pending_report(reason, missing=None, status="CHOW_INPUT_INCOMPLETE", extra=None):
    missing = missing or []
    slots = exceptional_slots()
    RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_RULES_TEMPLATE_PENDING_CHOW_INPUT", "Generated by compute_exceptional_rules_from_chow.sage; full Chow input not complete."), indent=2, sort_keys=True))
    report = {"status": status, "reason": reason, "missing_keys": missing, "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": 0}
    if extra:
        report.update(extra)
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))

def validate_fraction(value, key):
    try:
        Fraction(str(value))
    except Exception as exc:
        raise ValueError("Non-rational value for %s: %r (%s)" % (key, value, exc))
    return value

def write_verified_rules(rules, source, mode, input_status):
    slots = exceptional_slots()
    rule_file = {
        "schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1",
        "status": "EXCEPTIONAL_SECTOR_VERIFIED",
        "resolution_chamber": "Esole-Yau Ewx",
        "source": source,
        "mode": mode,
        "input_status_at_compute_time": input_status,
        "rules": rules,
        "required_rules": {},
        "rule_count": len(rules),
        "required_rule_count": 0,
        "total_exceptional_slots": len(slots),
        "reduction_stats": stats
    }
    RULES_OUT.write_text(json.dumps(rule_file, indent=2, sort_keys=True))
    report = {
        "status": "EXCEPTIONAL_RULES_COMPUTED_AND_VERIFIED",
        "mode": mode,
        "input_status_at_compute_time": input_status,
        "input_file": str(INPUT),
        "rules_output": str(RULES_OUT),
        "exceptional_slots": len(slots),
        "computed_rules": len(rules),
        "missing_values": 0,
        "reduction_stats": stats
    }
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))

def try_direct_values(chow, slots):
    values = chow.get("exceptional_intersection_values", {}) or {}
    if not values:
        return None
    missing = [k for k in slots if k not in values]
    if missing:
        partial = {k: validate_fraction(values[k], k) for k in slots if k in values}
        RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_RULE_KEYS_POPULATED_VALUES_PENDING", "Resolved ambient Chow input present, but exceptional_intersection_values did not cover every required monomial.", rules=partial, missing_values=missing), indent=2, sort_keys=True))
        report = {"status": "EXCEPTIONAL_VALUES_INCOMPLETE", "mode": "direct_exceptional_intersection_values", "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": len(partial), "missing_values": len(missing), "missing_values_sample": missing[:100]}
        REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
        print(json.dumps(report, indent=2, sort_keys=True))
        raise SystemExit(0)
    return {k: validate_fraction(values[k], k) for k in slots}

def sage_eval(expr, names):
    return eval(expr, {"__builtins__": {}}, names)

def monomial_from_key(key, divisor_lifts, names):
    prod = names["ONE"]
    for d in key.split(","):
        lift = divisor_lifts.get(d)
        if lift is None:
            raise KeyError("No divisor_lift for %s" % d)
        prod *= sage_eval(lift, names)
    return prod

def cartan_count(mon_parts):
    return sum(1 for p in mon_parts if p in CARTAN)

def has_zero_section(mon_parts):
    return any(p in ZERO_SECTION_NAMES for p in mon_parts)

def surf_pair(a, b):
    if a == "H" and b == "H":
        return Fraction(1)
    if a.startswith("E") and b.startswith("E") and a == b:
        return Fraction(-1)
    return Fraction(0)

def k_pair(name):
    if name == "H":
        return Fraction(-3)
    if name.startswith("E"):
        return Fraction(-1)
    return Fraction(0)

def k_square():
    return Fraction(1)

def b3_triple(a, b, c):
    names = [a, b, c]
    rcount = names.count("R")
    surf = [x for x in names if x != "R"]
    if rcount == 0:
        return Fraction(0)
    if rcount == 1:
        if len(surf) != 2:
            return Fraction(0)
        return surf_pair(surf[0], surf[1])
    if rcount == 2:
        if len(surf) != 1:
            return k_square()
        return k_pair(surf[0])
    if rcount == 3:
        return k_square()
    return Fraction(0)

def cartan_pair_pushforward_value(mon_parts):
    cart = [p for p in mon_parts if p in CARTAN]
    non = [p for p in mon_parts if p not in CARTAN]
    if len(cart) == 2 and len(non) == 2 and all(p in BASE_NAMES for p in non):
        i = int(cart[0][1:]) - 1
        j = int(cart[1][1:]) - 1
        stats["cartan_pair_pushforward_terms"] += 1
        return Fraction(-A4[i][j]) * b3_triple("R", non[0], non[1])
    return None

def make_aux_subs(names):
    def n(x):
        return names[x]
    subs = {}
    if "z" in names and "Z" in names:
        subs[n("z")] = n("Z")
    if "w" in names and "R" in names:
        subs[n("w")] = n("R")
    if all(k in names for k in ["R", "H"] + [f"E{i}" for i in range(1, 9)]):
        R = n("R"); H = n("H")
        Es = [n(f"E{i}") for i in range(1, 9)]
        def cls(aR, aH, aE):
            out = aR*R + aH*H
            for E in Es:
                out += aE*E
            return out
        beta5_cls = cls(2, 6, -2)
        beta4_cls = cls(3, 12, -4)
        beta3_cls = cls(4, 18, -6)
        beta2_cls = cls(5, 24, -8)
        beta0_cls = cls(7, 36, -12)
        if "beta5" in names: subs[n("beta5")] = beta5_cls
        if "beta4" in names: subs[n("beta4")] = beta4_cls
        if "beta3" in names: subs[n("beta3")] = beta3_cls
        if "beta2" in names: subs[n("beta2")] = beta2_cls
        if "beta0" in names: subs[n("beta0")] = beta0_cls
        if "Z" in names:
            x_cls = n("Z") + cls(4, 12, -4)
            y_cls = n("Z") + cls(6, 18, -6)
            if "x" in names: subs[n("x")] = x_cls
            if "y" in names: subs[n("y")] = y_cls
            # Important class-level correction: s and t are local equations whose
            # summands have common section classes. For Chow integration use the
            # common divisor class, not the local polynomial expansion.
            if "s" in names: subs[n("s")] = y_cls
            if "t" in names: subs[n("t")] = x_cls
    return subs

def substitute_auxiliary(poly, aux_subs):
    if not aux_subs:
        return poly
    out = poly
    # No Groebner reduction after class substitution: reduction may reintroduce
    # auxiliary variables because of the chosen leading terms. Integration needs
    # divisor-class expansion in the basis variables.
    for _ in range(2):
        out = out.subs(aux_subs)
        stats["auxiliary_substitution_passes"] += 1
    return out

def integrate_normal_form(poly, top_values, names, gb, aux_subs):
    total = Fraction(0)
    poly = substitute_auxiliary(poly, aux_subs)
    for exp, coeff in poly.dict().items():
        mon_parts = []
        for var, power in zip(names["__varlist__"], exp):
            mon_parts.extend([var] * int(power))
        mon_key = "*".join(mon_parts) if mon_parts else "1"
        coeff_q = Fraction(str(coeff))
        if mon_key in top_values:
            total += coeff_q * Fraction(str(top_values[mon_key]))
            continue
        if has_zero_section(mon_parts) and cartan_count(mon_parts) >= 1:
            stats["zero_section_cartan_disjoint_terms"] += 1
            continue
        cp = cartan_pair_pushforward_value(mon_parts)
        if cp is not None:
            total += coeff_q * cp
            continue
        if cartan_count(mon_parts) == 1:
            stats["single_cartan_pushforward_zero_terms"] += 1
            continue
        if cartan_count(mon_parts) >= 3:
            stats["higher_cartan_unresolved_terms"] += 1
        if coeff != 0:
            raise KeyError("No integration value for normal-form monomial %s" % mon_key)
    return total

def try_sage_quotient_mode(chow, slots):
    mode = chow.get("sage_polynomial_mode")
    if not mode:
        return None
    if PolynomialRing is None:
        write_pending_report("Sage PolynomialRing unavailable in this runtime.", ["sage.all.PolynomialRing"])
        raise SystemExit(0)
    required_mode_keys = ["variables", "quotient_ideal_generators", "divisor_lifts", "integration_functional"]
    missing = [k for k in required_mode_keys if k not in mode]
    if missing:
        write_pending_report("sage_polynomial_mode lacks required keys.", missing)
        raise SystemExit(0)
    variables = mode["variables"]
    if not variables:
        write_pending_report("sage_polynomial_mode.variables is empty.", ["variables"])
        raise SystemExit(0)
    R = PolynomialRing(QQ, variables, order="degrevlex")
    names = {str(v): g for v, g in zip(variables, R.gens())}
    names["ONE"] = R(1)
    names["__varlist__"] = variables
    divisor_lifts = mode["divisor_lifts"]
    missing_lifts = [d for d in basis if d not in divisor_lifts]
    if missing_lifts:
        write_pending_report("sage_polynomial_mode.divisor_lifts missing basis divisors.", missing_lifts)
        raise SystemExit(0)
    ideal_exprs = []
    ideal_exprs.extend(mode.get("quotient_ideal_generators", []))
    ideal_exprs.extend(chow.get("sr_ideal_generators", []))
    ideal_exprs.extend(chow.get("linear_equivalence_generators", []))
    pt = chow.get("proper_transform_class")
    if isinstance(pt, str) and pt.strip():
        ideal_exprs.append(pt)
    hyp = chow.get("hypersurface_class")
    if isinstance(hyp, str) and hyp.strip() and mode.get("include_hypersurface_as_relation", False):
        ideal_exprs.append(hyp)
    if not ideal_exprs:
        write_pending_report("No quotient ideal generators supplied; exact SR/linear/proper-transform relations are absent.", ["sage_polynomial_mode.quotient_ideal_generators", "sr_ideal_generators", "linear_equivalence_generators", "proper_transform_class"])
        raise SystemExit(0)
    try:
        ideal_gens = [sage_eval(expr, names) for expr in ideal_exprs]
        I = R.ideal(ideal_gens)
        gb = I.groebner_basis()
    except Exception as exc:
        write_pending_report("Could not build quotient ideal/Groebner basis: %s" % exc, ["quotient_ideal_generators"], extra={"exception": str(exc)})
        raise SystemExit(0)
    top_values = mode.get("integration_functional", {}).get("top_monomial_values", {})
    if not top_values:
        write_pending_report("integration_functional.top_monomial_values is empty; no integration map is available for normal forms.", ["integration_functional.top_monomial_values"])
        raise SystemExit(0)
    aux_subs = make_aux_subs(names)
    rules = {}
    failed = {}
    for key in slots:
        try:
            poly = monomial_from_key(key, divisor_lifts, names)
            normal = poly.reduce(gb)
            val = integrate_normal_form(normal, top_values, names, gb, aux_subs)
            rules[key] = int(val) if val.denominator == 1 else str(val)
        except Exception as exc:
            failed[key] = str(exc)
    if failed:
        RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_QUOTIENT_REDUCTION_INCOMPLETE", "Sage quotient mode ran but did not reduce/integrate every exceptional monomial.", rules=rules, missing_values=list(failed.keys())), indent=2, sort_keys=True))
        report = {"status": "QUOTIENT_REDUCTION_INCOMPLETE", "mode": "sage_polynomial_mode", "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": len(rules), "failed_rules": len(failed), "failed_sample": dict(list(failed.items())[:50]), "reduction_stats": stats}
        REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
        print(json.dumps(report, indent=2, sort_keys=True))
        raise SystemExit(0)
    return rules

if not INPUT.exists():
    write_pending_report("Missing resolved ambient Chow input file.", [str(INPUT)])
    raise SystemExit(0)
try:
    chow = json.loads(INPUT.read_text())
except Exception as exc:
    write_pending_report("Could not parse resolved ambient Chow input JSON: %s" % exc)
    raise SystemExit(0)
missing = [k for k in required_keys if k not in chow]
if missing:
    write_pending_report("Resolved ambient Chow input lacks required keys.", missing)
    raise SystemExit(0)
input_status = chow.get("status", "STATUS_NOT_SET")
slots = exceptional_slots()
rules = try_direct_values(chow, slots)
if rules is not None:
    write_verified_rules(rules, "Direct exceptional_intersection_values table in data/esole_yau_ewx_resolved_ambient_chow.json.", "direct_exceptional_intersection_values", input_status)
    raise SystemExit(0)
rules = try_sage_quotient_mode(chow, slots)
if rules is not None:
    write_verified_rules(rules, "Sage quotient presentation plus class-level auxiliary substitution, Cartan-pair pushforward, and named vanishing rules in data/esole_yau_ewx_resolved_ambient_chow.json.", "sage_polynomial_mode", input_status)
    raise SystemExit(0)
write_pending_report("No exceptional_intersection_values table and no sage_polynomial_mode presentation supplied.", ["exceptional_intersection_values", "sage_polynomial_mode"])
