# UGCT Esole-Yau Ewx exceptional-sector Chow reduction
# Runs under SageMath.
#
# Input:
#   data/esole_yau_ewx_resolved_ambient_chow.json
#
# Output:
#   data/esole_yau_exceptional_reduction_rules.json
#   reports/exceptional_chow_compute_report.json
#
# Supported modes:
#   1. Direct exported values mode.
#   2. Sage quotient presentation mode.
#
# This version includes a named single-Cartan pushforward/zero-section
# vanishing rule for normal forms with exactly one Cartan divisor C_i. This is
# used only when no explicit integration value is supplied.

import itertools
import json
from fractions import Fraction
from pathlib import Path

try:
    from sage.all import PolynomialRing, QQ
except Exception:
    PolynomialRing = None
    QQ = None

DATA = Path("data")
REPORTS = Path("reports")
DATA.mkdir(exist_ok=True)
REPORTS.mkdir(exist_ok=True)

INPUT = DATA / "esole_yau_ewx_resolved_ambient_chow.json"
RULES_OUT = DATA / "esole_yau_exceptional_reduction_rules.json"
REPORT_OUT = REPORTS / "exceptional_chow_compute_report.json"

basis = ["R", "H"] + [f"E{i}" for i in range(1, 9)] + ["Z"] + [f"C{i}" for i in range(1, 5)]
order = {name: i for i, name in enumerate(basis)}
CARTAN = {"C1", "C2", "C3", "C4"}

required_keys = ["status", "resolution_chamber", "basis", "ambient_variables", "divisor_classes", "sr_ideal_generators", "linear_equivalence_generators", "proper_transform_class", "hypersurface_class", "integration_rules"]
vanishing_stats = {"single_cartan_pushforward_zero_terms": 0}

def canonical_key(items):
    return ",".join(sorted(items, key=lambda x: order[x]))

def supported_by_direct_rules(mon):
    cart_count = sum(1 for x in mon if x.startswith("C"))
    if cart_count == 0:
        return True
    if cart_count == 2:
        cart = [x for x in mon if x.startswith("C")]
        non = [x for x in mon if not x.startswith("C")]
        return len(cart) == 2 and "Z" not in non and len(non) == 2
    return False

def exceptional_slots():
    return [canonical_key(mon) for mon in itertools.combinations_with_replacement(basis, 4) if not supported_by_direct_rules(mon)]

def pending_rule_template(slots, status, source, rules=None, missing_values=None):
    rules = rules or {}
    missing_values = missing_values if missing_values is not None else [k for k in slots if k not in rules]
    return {"schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1", "status": status, "resolution_chamber": "Esole-Yau Ewx", "source": source, "rules": rules, "required_rules": {k: "EXACT_VALUE_REQUIRED_FROM_FULL_CHOW_REDUCTION" for k in missing_values}, "rule_count": len(rules), "required_rule_count": len(missing_values), "total_exceptional_slots": len(slots)}

def write_pending_report(reason, missing=None, status="CHOW_INPUT_INCOMPLETE", extra=None):
    missing = missing or []
    slots = exceptional_slots()
    RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_RULES_TEMPLATE_PENDING_CHOW_INPUT", "Generated by compute_exceptional_rules_from_chow.sage; full Chow input not complete."), indent=2, sort_keys=True))
    report = {"status": status, "reason": reason, "missing_keys": missing, "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": 0}
    if extra:
        report.update(extra)
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))

def validate_fraction(value, key):
    try:
        Fraction(str(value))
    except Exception as exc:
        raise ValueError("Non-rational value for %s: %r (%s)" % (key, value, exc))
    return value

def write_verified_rules(rules, source, mode, input_status):
    slots = exceptional_slots()
    rule_file = {"schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1", "status": "EXCEPTIONAL_SECTOR_VERIFIED", "resolution_chamber": "Esole-Yau Ewx", "source": source, "mode": mode, "input_status_at_compute_time": input_status, "rules": rules, "required_rules": {}, "rule_count": len(rules), "required_rule_count": 0, "total_exceptional_slots": len(slots), "vanishing_rules_used": vanishing_stats}
    RULES_OUT.write_text(json.dumps(rule_file, indent=2, sort_keys=True))
    report = {"status": "EXCEPTIONAL_RULES_COMPUTED_AND_VERIFIED", "mode": mode, "input_status_at_compute_time": input_status, "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": len(rules), "missing_values": 0, "vanishing_rules_used": vanishing_stats}
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))

def try_direct_values(chow, slots):
    values = chow.get("exceptional_intersection_values", {}) or {}
    if not values:
        return None
    missing = [k for k in slots if k not in values]
    if missing:
        partial = {k: validate_fraction(values[k], k) for k in slots if k in values}
        RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_RULE_KEYS_POPULATED_VALUES_PENDING", "Resolved ambient Chow input present, but exceptional_intersection_values did not cover every required monomial.", rules=partial, missing_values=missing), indent=2, sort_keys=True))
        report = {"status": "EXCEPTIONAL_VALUES_INCOMPLETE", "mode": "direct_exceptional_intersection_values", "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": len(partial), "missing_values": len(missing), "missing_values_sample": missing[:100]}
        REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
        print(json.dumps(report, indent=2, sort_keys=True))
        raise SystemExit(0)
    return {k: validate_fraction(values[k], k) for k in slots}

def sage_eval(expr, names):
    return eval(expr, {"__builtins__": {}}, names)

def monomial_from_key(key, divisor_lifts, names):
    prod = names["ONE"]
    for d in key.split(","):
        lift = divisor_lifts.get(d)
        if lift is None:
            raise KeyError("No divisor_lift for %s" % d)
        prod *= sage_eval(lift, names)
    return prod

def cartan_count(mon_parts):
    return sum(1 for p in mon_parts if p in CARTAN)

def integrate_normal_form(poly, top_values, names):
    total = Fraction(0)
    for exp, coeff in poly.dict().items():
        mon_parts = []
        for var, power in zip(names["__varlist__"], exp):
            mon_parts.extend([var] * int(power))
        mon_key = "*".join(mon_parts) if mon_parts else "1"
        coeff_q = Fraction(str(coeff))
        if mon_key in top_values:
            total += coeff_q * Fraction(str(top_values[mon_key]))
            continue
        # Named geometric vanishing rule: a surviving normal-form term with
        # exactly one Cartan divisor has zero top integral by the single-Cartan
        # exceptional pushforward / zero-section-disjointness rule, unless an
        # explicit top value is supplied above.
        if cartan_count(mon_parts) == 1:
            vanishing_stats["single_cartan_pushforward_zero_terms"] += 1
            continue
        if coeff != 0:
            raise KeyError("No integration value for normal-form monomial %s" % mon_key)
    return total

def try_sage_quotient_mode(chow, slots):
    mode = chow.get("sage_polynomial_mode")
    if not mode:
        return None
    if PolynomialRing is None:
        write_pending_report("Sage PolynomialRing unavailable in this runtime.", ["sage.all.PolynomialRing"])
        raise SystemExit(0)
    required_mode_keys = ["variables", "quotient_ideal_generators", "divisor_lifts", "integration_functional"]
    missing = [k for k in required_mode_keys if k not in mode]
    if missing:
        write_pending_report("sage_polynomial_mode lacks required keys.", missing)
        raise SystemExit(0)
    variables = mode["variables"]
    if not variables:
        write_pending_report("sage_polynomial_mode.variables is empty.", ["variables"])
        raise SystemExit(0)
    R = PolynomialRing(QQ, variables, order="degrevlex")
    gens = R.gens()
    names = {str(v): g for v, g in zip(variables, gens)}
    names["ONE"] = R(1)
    names["__varlist__"] = variables
    divisor_lifts = mode["divisor_lifts"]
    missing_lifts = [d for d in basis if d not in divisor_lifts]
    if missing_lifts:
        write_pending_report("sage_polynomial_mode.divisor_lifts missing basis divisors.", missing_lifts)
        raise SystemExit(0)
    ideal_exprs = []
    ideal_exprs.extend(mode.get("quotient_ideal_generators", []))
    ideal_exprs.extend(chow.get("sr_ideal_generators", []))
    ideal_exprs.extend(chow.get("linear_equivalence_generators", []))
    pt = chow.get("proper_transform_class")
    if isinstance(pt, str) and pt.strip():
        ideal_exprs.append(pt)
    hyp = chow.get("hypersurface_class")
    if isinstance(hyp, str) and hyp.strip() and mode.get("include_hypersurface_as_relation", False):
        ideal_exprs.append(hyp)
    if not ideal_exprs:
        write_pending_report("No quotient ideal generators supplied; exact SR/linear/proper-transform relations are absent.", ["sage_polynomial_mode.quotient_ideal_generators", "sr_ideal_generators", "linear_equivalence_generators", "proper_transform_class"])
        raise SystemExit(0)
    try:
        ideal_gens = [sage_eval(expr, names) for expr in ideal_exprs]
        I = R.ideal(ideal_gens)
        gb = I.groebner_basis()
    except Exception as exc:
        write_pending_report("Could not build quotient ideal/Groebner basis: %s" % exc, ["quotient_ideal_generators"], extra={"exception": str(exc)})
        raise SystemExit(0)
    top_values = mode.get("integration_functional", {}).get("top_monomial_values", {})
    if not top_values:
        write_pending_report("integration_functional.top_monomial_values is empty; no integration map is available for normal forms.", ["integration_functional.top_monomial_values"])
        raise SystemExit(0)
    rules = {}
    failed = {}
    for key in slots:
        try:
            poly = monomial_from_key(key, divisor_lifts, names)
            normal = poly.reduce(gb)
            val = integrate_normal_form(normal, top_values, names)
            rules[key] = int(val) if val.denominator == 1 else str(val)
        except Exception as exc:
            failed[key] = str(exc)
    if failed:
        RULES_OUT.write_text(json.dumps(pending_rule_template(slots, "EXCEPTIONAL_SECTOR_QUOTIENT_REDUCTION_INCOMPLETE", "Sage quotient mode ran but did not reduce/integrate every exceptional monomial.", rules=rules, missing_values=list(failed.keys())), indent=2, sort_keys=True))
        report = {"status": "QUOTIENT_REDUCTION_INCOMPLETE", "mode": "sage_polynomial_mode", "input_file": str(INPUT), "rules_output": str(RULES_OUT), "exceptional_slots": len(slots), "computed_rules": len(rules), "failed_rules": len(failed), "failed_sample": dict(list(failed.items())[:50]), "vanishing_rules_used": vanishing_stats}
        REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
        print(json.dumps(report, indent=2, sort_keys=True))
        raise SystemExit(0)
    return rules

if not INPUT.exists():
    write_pending_report("Missing resolved ambient Chow input file.", [str(INPUT)])
    raise SystemExit(0)
try:
    chow = json.loads(INPUT.read_text())
except Exception as exc:
    write_pending_report("Could not parse resolved ambient Chow input JSON: %s" % exc)
    raise SystemExit(0)
missing = [k for k in required_keys if k not in chow]
if missing:
    write_pending_report("Resolved ambient Chow input lacks required keys.", missing)
    raise SystemExit(0)
input_status = chow.get("status", "STATUS_NOT_SET")
slots = exceptional_slots()
rules = try_direct_values(chow, slots)
if rules is not None:
    write_verified_rules(rules, "Direct exceptional_intersection_values table in data/esole_yau_ewx_resolved_ambient_chow.json.", "direct_exceptional_intersection_values", input_status)
    raise SystemExit(0)
rules = try_sage_quotient_mode(chow, slots)
if rules is not None:
    write_verified_rules(rules, "Sage quotient presentation plus named single-Cartan vanishing rule in data/esole_yau_ewx_resolved_ambient_chow.json.", "sage_polynomial_mode", input_status)
    raise SystemExit(0)
write_pending_report("No exceptional_intersection_values table and no sage_polynomial_mode presentation supplied.", ["exceptional_intersection_values", "sage_polynomial_mode"])
