# UGCT Esole-Yau Ewx exceptional-sector Chow reduction
#
# This script is the missing bridge between the full resolved ambient Chow-ring
# data and the exceptional-rule file consumed by run_chow_tensor.sage.
#
# Input:
#   data/esole_yau_ewx_resolved_ambient_chow.json
#
# Output:
#   data/esole_yau_exceptional_reduction_rules.json
#   reports/exceptional_chow_compute_report.json
#
# The input file must provide a complete quotient presentation of the resolved
# ambient Chow ring plus an integration map. This script refuses to invent
# values: if the required ideals/integration rules are absent, it writes a
# CHOW_INPUT_INCOMPLETE report and leaves the rule file pending.

import itertools
import json
import os
from fractions import Fraction
from pathlib import Path

DATA = Path("data")
REPORTS = Path("reports")
DATA.mkdir(exist_ok=True)
REPORTS.mkdir(exist_ok=True)

INPUT = DATA / "esole_yau_ewx_resolved_ambient_chow.json"
RULES_OUT = DATA / "esole_yau_exceptional_reduction_rules.json"
REPORT_OUT = REPORTS / "exceptional_chow_compute_report.json"

basis = ["R", "H"] + [f"E{i}" for i in range(1, 9)] + ["Z"] + [f"C{i}" for i in range(1, 5)]
order = {name: i for i, name in enumerate(basis)}

required_keys = [
    "status",
    "resolution_chamber",
    "basis",
    "ambient_variables",
    "divisor_classes",
    "sr_ideal_generators",
    "linear_equivalence_generators",
    "proper_transform_class",
    "hypersurface_class",
    "integration_rules"
]

def canonical_key(items):
    return ",".join(sorted(items, key=lambda x: order[x]))

def supported_by_direct_rules(mon):
    cart_count = sum(1 for x in mon if x.startswith("C"))
    if cart_count == 0:
        return True
    if cart_count == 2:
        cart = [x for x in mon if x.startswith("C")]
        non = [x for x in mon if not x.startswith("C")]
        return len(cart) == 2 and "Z" not in non and len(non) == 2
    return False

def exceptional_slots():
    out = []
    for mon in itertools.combinations_with_replacement(basis, 4):
        if not supported_by_direct_rules(mon):
            out.append(canonical_key(mon))
    return out

def write_pending_report(reason, missing=None):
    missing = missing or []
    slots = exceptional_slots()
    rule_template = {
        "schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1",
        "status": "EXCEPTIONAL_SECTOR_RULES_TEMPLATE_PENDING_CHOW_INPUT",
        "resolution_chamber": "Esole-Yau Ewx",
        "source": "Generated by compute_exceptional_rules_from_chow.sage; full Chow input not complete.",
        "rules": {},
        "required_rules": {k: "EXACT_VALUE_REQUIRED_FROM_FULL_CHOW_REDUCTION" for k in slots},
        "rule_count": 0,
        "required_rule_count": len(slots),
        "total_exceptional_slots": len(slots)
    }
    RULES_OUT.write_text(json.dumps(rule_template, indent=2, sort_keys=True))
    report = {
        "status": "CHOW_INPUT_INCOMPLETE",
        "reason": reason,
        "missing_keys": missing,
        "input_file": str(INPUT),
        "rules_output": str(RULES_OUT),
        "exceptional_slots": len(slots),
        "computed_rules": 0
    }
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))

if not INPUT.exists():
    write_pending_report("Missing resolved ambient Chow input file.", [str(INPUT)])
    raise SystemExit(0)

try:
    chow = json.loads(INPUT.read_text())
except Exception as exc:
    write_pending_report("Could not parse resolved ambient Chow input JSON: %s" % exc)
    raise SystemExit(0)

missing = [k for k in required_keys if k not in chow]
if missing:
    write_pending_report("Resolved ambient Chow input lacks required keys.", missing)
    raise SystemExit(0)

if chow.get("status") != "RESOLVED_AMBIENT_CHOW_DATA_VERIFIED":
    write_pending_report("Resolved ambient Chow input status is not RESOLVED_AMBIENT_CHOW_DATA_VERIFIED.", ["status"])
    raise SystemExit(0)

# Generic exact-reduction interface.
#
# Accepted simple mode:
#   If the input file already contains `exceptional_intersection_values`, this
#   script validates coverage and writes the rule file. This supports an
#   external Macaulay2/OSCAR/Sage reduction exporting exact values.
#
# Full quotient-ring symbolic mode can be added once the input file supplies
# Sage-parsable polynomial generators and an integration functional.
values = chow.get("exceptional_intersection_values", {})
slots = exceptional_slots()
missing_values = [k for k in slots if k not in values]

if missing_values:
    rule_template = {
        "schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1",
        "status": "EXCEPTIONAL_SECTOR_RULE_KEYS_POPULATED_VALUES_PENDING",
        "resolution_chamber": "Esole-Yau Ewx",
        "source": "Resolved ambient Chow input present, but exceptional_intersection_values did not cover every required monomial.",
        "rules": {k: values[k] for k in slots if k in values},
        "required_rules": {k: "EXACT_VALUE_REQUIRED_FROM_FULL_CHOW_REDUCTION" for k in missing_values},
        "rule_count": len(slots) - len(missing_values),
        "required_rule_count": len(missing_values),
        "total_exceptional_slots": len(slots)
    }
    RULES_OUT.write_text(json.dumps(rule_template, indent=2, sort_keys=True))
    report = {
        "status": "EXCEPTIONAL_VALUES_INCOMPLETE",
        "input_file": str(INPUT),
        "rules_output": str(RULES_OUT),
        "exceptional_slots": len(slots),
        "computed_rules": len(slots) - len(missing_values),
        "missing_values": len(missing_values),
        "missing_values_sample": missing_values[:100]
    }
    REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
    print(json.dumps(report, indent=2, sort_keys=True))
    raise SystemExit(0)

# Validate exact rational values.
rules = {}
for k in slots:
    val = values[k]
    try:
        Fraction(str(val))
    except Exception as exc:
        raise ValueError("Non-rational exceptional value for %s: %r (%s)" % (k, val, exc))
    rules[k] = val

rule_file = {
    "schema_version": "UGCT_ESOLE_YAU_EXCEPTIONAL_RULES_V1",
    "status": "EXCEPTIONAL_SECTOR_VERIFIED",
    "resolution_chamber": "Esole-Yau Ewx",
    "source": "Computed from data/esole_yau_ewx_resolved_ambient_chow.json by compute_exceptional_rules_from_chow.sage.",
    "rules": rules,
    "required_rules": {},
    "rule_count": len(rules),
    "required_rule_count": 0,
    "total_exceptional_slots": len(slots)
}
RULES_OUT.write_text(json.dumps(rule_file, indent=2, sort_keys=True))
report = {
    "status": "EXCEPTIONAL_RULES_COMPUTED_AND_VERIFIED",
    "input_file": str(INPUT),
    "rules_output": str(RULES_OUT),
    "exceptional_slots": len(slots),
    "computed_rules": len(rules),
    "missing_values": 0
}
REPORT_OUT.write_text(json.dumps(report, indent=2, sort_keys=True))
print(json.dumps(report, indent=2, sort_keys=True))
